version: '1.1'

services:

 phpmyadmin:
    image:phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Prueba  
 